### ISSUE TITLE
Practice Tool crashes on start after latest update

### ISSUE THREAD

**Issue by davidlivingrooms** [veeenu/eldenring-practice-tool#52]
The recent Elden Ring patch may have broken something. The game itself does not crash, but the practice tool doesn't hook like it used to.
Here's the content of the log
```2023-07-28T14:19:29.683965Z  INFO ThreadId(01) libeldenring::version: lib\libeldenring\src\version.rs:73: Version 2 0 0    
2023-07-28T14:19:29.684067Z ERROR ThreadId(01) libeldenring::codegen::base_addresses: lib\libeldenring\src\codegen\base_addresses.rs:111: Unrecognized version 2.00.0    
2023-07-28T14:19:29.691314Z ERROR ThreadId(01) panic: C:\Users\andrea\.cargo\registry\src\index.crates.io-6f17d22bba15001f\log-panics-2.1.0\src\lib.rs:130: thread '<unnamed>' panicked at 'explicit panic': lib\libeldenring\src\codegen\base_addresses.rs:112
   0: DllMain
   1: DllMain
   2: DllMain
   3: DllMain
   4: DllMain
   5: DllMain
   6: DllMain
   7: DllMain
   8: DllMain
   9: DllMain
  10: DllMain
  11: DllMain
  12: DllMain
  13: DllMain
  14: DllMain
  15: <unknown>
  16: DllMain
  17: <unknown>
  18: DllMain
  19: BaseThreadInitThunk
  20: RtlUserThreadStart
    
2023-07-28T14:19:29.692000Z ERROR ThreadId(02) panic: C:\Users\andrea\.cargo\registry\src\index.crates.io-6f17d22bba15001f\log-panics-2.1.0\src\lib.rs:130: thread '<unnamed>' panicked at 'Once instance has previously been poisoned': /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc\library\std\src\sync\lazy_lock.rs:91```

**Comment by rumd3x** [comment]
It has not been updated to the latest patch yet. Be patient.

**Comment by veeenu** [comment]
Updated. 🚀
